FROM eclipse-temurin:17-jre

ARG PROJECT_VERSION=0.1.0

RUN mkdir -p /home/app
WORKDIR /home/app
ENV SPRING_PROFILES_ACTIVE=dev
COPY target/shipping-service-v${PROJECT_VERSION}.jar shipping-service.jar
EXPOSE 8600
ENTRYPOINT ["java", "-jar", "shipping-service.jar"]